version: 2.1

executors:
  node_latest:
    docker:
    - image: circleci/node:latest
  node_lts:
    docker:
      - image: circleci/node:lts
  default_executor: node_latest

aliases:
  - &repo_path
    ~/monorepo
  - &defaults
    working_directory: *repo_path
  - &yarn_cache_key
    yarn-sha-{{ checksum "yarn.lock" }}
  - &ignore_non_dev_branches
    filters:
      tags:
        only: /.*/
      branches:
        ignore:
          - /release\/.*/
  - &execute_on_release
    filters:
      tags:
        only: /v?[0-9]+(\.[0-9]+)*/
      branches:
        ignore:
          - /.*/
  - &execute_on_release_prerelease
    filters:
      tags:
        only: /v?[0-9]+(\.[0-9]+)*([-+][a-zA-Z0-9]+)+([-+\.][a-zA-Z0-9-]+)*/
      branches:
        ignore:
          - /.*/

commands:
  restore_repo:
    description: Restore repository from workspace
    steps:
      - attach_workspace:
          at: *repo_path

jobs:
  prepare:
    <<: *defaults
    executor: default_executor
    steps:
      - checkout
      - restore_cache:
          key: *yarn_cache_key
      - run:
          name: Install monorepo dependencies
          command: yarn install --frozen-lockfile
      - run:
          name: Build projects
          command: yarn build
      - save_cache:
          key: *yarn_cache_key
          paths:
            - ~/.yarn
            - ~/.cache/yarn
            - node_modules
      - persist_to_workspace:
          root: *repo_path
          paths:
            - ./*

  lint:
    <<: *defaults
    executor: default_executor
    steps:
      - restore_repo
      - run:
          name: Lint code
          command: yarn lint

  test_node_latest:
    <<: *defaults
    executor: node_latest
    steps:
      - restore_repo
      - run:
          name: Test with Node (Latest)
          command: yarn test
      - run:
          name: Publish coverage
          command: yarn coverage:publish
  publish:
    <<: *defaults
    executor: default_executor
    steps:
      - restore_repo
      - run:
          name: 'Setup publish credentials'
          command: echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ~/.npmrc
      - run:
          name: Publish
          command: yarn release:publish --yes --registry=https://registry.npmjs.org

  publish_prerelease:
    <<: *defaults
    executor: default_executor
    steps:
      - restore_repo
      - run:
          name: 'Setup publish credentials'
          command: echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ~/.npmrc
      - run:
          name: Publish prerelease
          command: yarn release:publish-prerelease --yes --registry=https://registry.npmjs.org

workflows:
  version: 2
  workflow:
    jobs:
      - prepare:
          <<: *ignore_non_dev_branches
      - lint:
          requires:
            - prepare
          <<: *ignore_non_dev_branches
      - test_node_latest:
          requires:
            - prepare
            - lint
          <<: *ignore_non_dev_branches
      - publish:
          requires:
            - test_node_latest
          <<: *execute_on_release
      - publish_prerelease:
          requires:
            - test_node_latest
          <<: *execute_on_release_prerelease
